### ISSUE TITLE
ConnectionRefusedError: [Errno 111] Connection refused

### ISSUE THREAD

**Issue by jiawenquan** [ascribe/match3d#8]
My system version is ubuntu 18
Blender 2.79b
Python 3.5

Package         Version 
--------------- --------
certifi         2019.3.9
chardet         3.0.4   
cloudpickle     0.8.1   
cycler          0.10.0  
dask            1.2.0   
decorator       4.4.0   
elasticsearch   6.3.1   
idna            2.8     
image-match     1.1.2   
imageio         2.5.0   
kiwisolver      1.0.1   
match3d         0.0.1   
matplotlib      3.0.3   
networkx        2.3     
numpy           1.16.2  
Pillow          6.0.0   
pip             19.0.3  
pyparsing       2.4.0   
python-dateutil 2.8.0   
PyWavelets      1.0.3   
requests        2.21.0  
scikit-image    0.14.2  
scipy           1.2.1   
setuptools      40.8.0  
six             1.12.0  
toolz           0.9.0   
urllib3         1.25    

Blender quit
/home/jiawenquan/下载/blender-2.79b-linux-glibc219-x86_64/2.79/python/lib/python3.5/site-packages/skimage/io/_io.py:49: UserWarning: `as_grey` has been deprecated in favor of `as_gray`
  warn('`as_grey` has been deprecated in favor of `as_gray`')
POST http://localhost:9200/_bulk [status:N/A request:0.001s]
Traceback (most recent call last):
  File "/home/jiawenquan/下载/blender-2.79b-linux-glibc219-x86_64/2.79/python/lib/python3.5/site-packages/urllib3/connection.py", line 160, in _new_conn
    (self._dns_host, self.port), self.timeout, **extra_kw)
  File "/home/jiawenquan/下载/blender-2.79b-linux-glibc219-x86_64/2.79/python/lib/python3.5/site-packages/urllib3/util/connection.py", line 80, in create_connection
    raise err
  File "/home/jiawenquan/下载/blender-2.79b-linux-glibc219-x86_64/2.79/python/lib/python3.5/site-packages/urllib3/util/connection.py", line 70, in create_connection
    sock.connect(sa)
ConnectionRefusedError: [Errno 111] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/jiawenquan/下载/blender-2.79b-linux-glibc219-x86_64/2.79/python/lib/python3.5/site-packages/elasticsearch/connection/http_urllib3.py", line 172, in perform_request
    response = self.pool.urlopen(method, url, body, retries=Retry(False), headers=request_headers, **kw)
  File "/home/jiawenquan/下载/blender-2.79b-linux-glibc219-x86_64/2.79/python/lib/python3.5/site-packages/urllib3/connectionpool.py", line 641, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "/home/jiawenquan/下载/blender-2.79b-linux-glibc219-x86_64/2.79/python/lib/python3.5/site-packages/urllib3/util/retry.py", line 344, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "/home/jiawenquan/下载/blender-2.79b-linux-glibc219-x86_64/2.79/python/lib/python3.5/site-packages/urllib3/packages/six.py", line 686, in reraise
    raise value
  File "/home/jiawenquan/下载/blender-2.79b-linux-glibc219-x86_64/2.79/python/lib/python3.5/site-packages/urllib3/connectionpool.py", line 603, in urlopen
    chunked=chunked)
  File "/home/jiawenquan/下载/blender-2.79b-linux-glibc219-x86_64/2.79/python/lib/python3.5/site-packages/urllib3/connectionpool.py", line 355, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "/home/jiawenquan/下载/blender-2.79b-linux-glibc219-x86_64/2.79/python/lib/python3.5/http/client.py", line 1107, in request
    self._send_request(method, url, body, headers)
  File "/home/jiawenquan/下载/blender-2.79b-linux-glibc219-x86_64/2.79/python/lib/python3.5/http/client.py", line 1152, in _send_request
    self.endheaders(body)
  File "/home/jiawenquan/下载/blender-2.79b-linux-glibc219-x86_64/2.79/python/lib/python3.5/http/client.py", line 1103, in endheaders
    self._send_output(message_body)
  File "/home/jiawenquan/下载/blender-2.79b-linux-glibc219-x86_64/2.79/python/lib/python3.5/http/client.py", line 934, in _send_output
    self.send(msg)
  File "/home/jiawenquan/下载/blender-2.79b-linux-glibc219-x86_64/2.79/python/lib/python3.5/http/client.py", line 877, in send
    self.connect()
  File "/home/jiawenquan/下载/blender-2.79b-linux-glibc219-x86_64/2.79/python/lib/python3.5/site-packages/urllib3/connection.py", line 183, in connect
    conn = self._new_conn()
  File "/home/jiawenquan/下载/blender-2.79b-linux-glibc219-x86_64/2.79/python/lib/python3.5/site-packages/urllib3/connection.py", line 169, in _new_conn
    self, "Failed to establish a new connection: %s" % e)
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPConnection object at 0x7fbc13bbbda0>: Failed to establish a new connection: [Errno 111] Connection refused
POST http://localhost:9200/_bulk [status:N/A request:0.000s]
Traceback (most recent call last):
  File "/home/jiawenquan/下载/blender-2.79b-linux-glibc219-x86_64/2.79/python/lib/python3.5/site-packages/urllib3/connection.py", line 160, in _new_conn
    (self._dns_host, self.port), self.timeout, **extra_kw)
  File "/home/jiawenquan/下载/blender-2.79b-linux-glibc219-x86_64/2.79/python/lib/python3.5/site-packages/urllib3/util/connection.py", line 80, in create_connection
    raise err
  File "/home/jiawenquan/下载/blender-2.79b-linux-glibc219-x86_64/2.79/python/lib/python3.5/site-packages/urllib3/util/connection.py", line 70, in create_connection
    sock.connect(sa)
ConnectionRefusedError: [Errno 111] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/jiawenquan/下载/blender-2.79b-linux-glibc219-x86_64/2.79/python/lib/python3.5/site-packages/elasticsearch/connection/http_urllib3.py", line 172, in perform_request
    response = self.pool.urlopen(method, url, body, retries=Retry(False), headers=request_headers, **kw)
  File "/home/jiawenquan/下载/blender-2.79b-linux-glibc219-x86_64/2.79/python/lib/python3.5/site-packages/urllib3/connectionpool.py", line 641, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "/home/jiawenquan/下载/blender-2.79b-linux-glibc219-x86_64/2.79/python/lib/python3.5/site-packages/urllib3/util/retry.py", line 344, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "/home/jiawenquan/下载/blender-2.79b-linux-glibc219-x86_64/2.79/python/lib/python3.5/site-packages/urllib3/packages/six.py", line 686, in reraise
    raise value
  File "/home/jiawenquan/下载/blender-2.79b-linux-glibc219-x86_64/2.79/python/lib/python3.5/site-packages/urllib3/connectionpool.py", line 603, in urlopen
    chunked=chunked)
  File "/home/jiawenquan/下载/blender-2.79b-linux-glibc219-x86_64/2.79/python/lib/python3.5/site-packages/urllib3/connectionpool.py", line 355, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "/home/jiawenquan/下载/blender-2.79b-linux-glibc219-x86_64/2.79/python/lib/python3.5/http/client.py", line 1107, in request
    self._send_request(method, url, body, headers)
  File "/home/jiawenquan/下载/blender-2.79b-linux-glibc219-x86_64/2.79/python/lib/python3.5/http/client.py", line 1152, in _send_request
    self.endheaders(body)
  File "/home/jiawenquan/下载/blender-2.79b-linux-glibc219-x86_64/2.79/python/lib/python3.5/http/client.py", line 1103, in endheaders
    self._send_output(message_body)
  File "/home/jiawenquan/下载/blender-2.79b-linux-glibc219-x86_64/2.79/python/lib/python3.5/http/client.py", line 934, in _send_output
    self.send(msg)
  File "/home/jiawenquan/下载/blender-2.79b-linux-glibc219-x86_64/2.79/python/lib/python3.5/http/client.py", line 877, in send
    self.connect()
  File "/home/jiawenquan/下载/blender-2.79b-linux-glibc219-x86_64/2.79/python/lib/python3.5/site-packages/urllib3/connection.py", line 183, in connect
    conn = self._new_conn()
  File "/home/jiawenquan/下载/blender-2.79b-linux-glibc219-x86_64/2.79/python/lib/python3.5/site-packages/urllib3/connection.py", line 169, in _new_conn
    self, "Failed to establish a new connection: %s" % e)
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPConnection object at 0x7fbc13b47588>: Failed to establish a new connection: [Errno 111] Connection refused
POST http://localhost:9200/_bulk [status:N/A request:0.000s]
Traceback (most recent call last):
  File "/home/jiawenquan/下载/blender-2.79b-linux-glibc219-x86_64/2.79/python/lib/python3.5/site-packages/urllib3/connection.py", line 160, in _new_conn
    (self._dns_host, self.port), self.timeout, **extra_kw)
  File "/home/jiawenquan/下载/blender-2.79b-linux-glibc219-x86_64/2.79/python/lib/python3.5/site-packages/urllib3/util/connection.py", line 80, in create_connection
    raise err
  File "/home/jiawenquan/下载/blender-2.79b-linux-glibc219-x86_64/2.79/python/lib/python3.5/site-packages/urllib3/util/connection.py", line 70, in create_connection
    sock.connect(sa)
ConnectionRefusedError: [Errno 111] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/jiawenquan/下载/blender-2.79b-linux-glibc219-x86_64/2.79/python/lib/python3.5/site-packages/elasticsearch/connection/http_urllib3.py", line 172, in perform_request
    response = self.pool.urlopen(method, url, body, retries=Retry(False), headers=request_headers, **kw)
  File "/home/jiawenquan/下载/blender-2.79b-linux-glibc219-x86_64/2.79/python/lib/python3.5/site-packages/urllib3/connectionpool.py", line 641, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "/home/jiawenquan/下载/blender-2.79b-linux-glibc219-x86_64/2.79/python/lib/python3.5/site-packages/urllib3/util/retry.py", line 344, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "/home/jiawenquan/下载/blender-2.79b-linux-glibc219-x86_64/2.79/python/lib/python3.5/site-packages/urllib3/packages/six.py", line 686, in reraise
    raise value
  File "/home/jiawenquan/下载/blender-2.79b-linux-glibc219-x86_64/2.79/python/lib/python3.5/site-packages/urllib3/connectionpool.py", line 603, in urlopen
    chunked=chunked)
  File "/home/jiawenquan/下载/blender-2.79b-linux-glibc219-x86_64/2.79/python/lib/python3.5/site-packages/urllib3/connectionpool.py", line 355, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "/home/jiawenquan/下载/blender-2.79b-linux-glibc219-x86_64/2.79/python/lib/python3.5/http/client.py", line 1107, in request
    self._send_request(method, url, body, headers)
  File "/home/jiawenquan/下载/blender-2.79b-linux-glibc219-x86_64/2.79/python/lib/python3.5/http/client.py", line 1152, in _send_request
    self.endheaders(body)
  File "/home/jiawenquan/下载/blender-2.79b-linux-glibc219-x86_64/2.79/python/lib/python3.5/http/client.py", line 1103, in endheaders
    self._send_output(message_body)
  File "/home/jiawenquan/下载/blender-2.79b-linux-glibc219-x86_64/2.79/python/lib/python3.5/http/client.py", line 934, in _send_output
    self.send(msg)
  File "/home/jiawenquan/下载/blender-2.79b-linux-glibc219-x86_64/2.79/python/lib/python3.5/http/client.py", line 877, in send
    self.connect()
  File "/home/jiawenquan/下载/blender-2.79b-linux-glibc219-x86_64/2.79/python/lib/python3.5/site-packages/urllib3/connection.py", line 183, in connect
    conn = self._new_conn()
  File "/home/jiawenquan/下载/blender-2.79b-linux-glibc219-x86_64/2.79/python/lib/python3.5/site-packages/urllib3/connection.py", line 169, in _new_conn
    self, "Failed to establish a new connection: %s" % e)
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPConnection object at 0x7fbc13b478d0>: Failed to establish a new connection: [Errno 111] Connection refused
POST http://localhost:9200/_bulk [status:N/A request:0.000s]
Traceback (most recent call last):
  File "/home/jiawenquan/下载/blender-2.79b-linux-glibc219-x86_64/2.79/python/lib/python3.5/site-packages/urllib3/connection.py", line 160, in _new_conn
    (self._dns_host, self.port), self.timeout, **extra_kw)
  File "/home/jiawenquan/下载/blender-2.79b-linux-glibc219-x86_64/2.79/python/lib/python3.5/site-packages/urllib3/util/connection.py", line 80, in create_connection
    raise err
  File "/home/jiawenquan/下载/blender-2.79b-linux-glibc219-x86_64/2.79/python/lib/python3.5/site-packages/urllib3/util/connection.py", line 70, in create_connection
    sock.connect(sa)
ConnectionRefusedError: [Errno 111] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/jiawenquan/下载/blender-2.79b-linux-glibc219-x86_64/2.79/python/lib/python3.5/site-packages/elasticsearch/connection/http_urllib3.py", line 172, in perform_request
    response = self.pool.urlopen(method, url, body, retries=Retry(False), headers=request_headers, **kw)
  File "/home/jiawenquan/下载/blender-2.79b-linux-glibc219-x86_64/2.79/python/lib/python3.5/site-packages/urllib3/connectionpool.py", line 641, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "/home/jiawenquan/下载/blender-2.79b-linux-glibc219-x86_64/2.79/python/lib/python3.5/site-packages/urllib3/util/retry.py", line 344, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "/home/jiawenquan/下载/blender-2.79b-linux-glibc219-x86_64/2.79/python/lib/python3.5/site-packages/urllib3/packages/six.py", line 686, in reraise
    raise value
  File "/home/jiawenquan/下载/blender-2.79b-linux-glibc219-x86_64/2.79/python/lib/python3.5/site-packages/urllib3/connectionpool.py", line 603, in urlopen
    chunked=chunked)
  File "/home/jiawenquan/下载/blender-2.79b-linux-glibc219-x86_64/2.79/python/lib/python3.5/site-packages/urllib3/connectionpool.py", line 355, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "/home/jiawenquan/下载/blender-2.79b-linux-glibc219-x86_64/2.79/python/lib/python3.5/http/client.py", line 1107, in request
    self._send_request(method, url, body, headers)
  File "/home/jiawenquan/下载/blender-2.79b-linux-glibc219-x86_64/2.79/python/lib/python3.5/http/client.py", line 1152, in _send_request
    self.endheaders(body)
  File "/home/jiawenquan/下载/blender-2.79b-linux-glibc219-x86_64/2.79/python/lib/python3.5/http/client.py", line 1103, in endheaders
    self._send_output(message_body)
  File "/home/jiawenquan/下载/blender-2.79b-linux-glibc219-x86_64/2.79/python/lib/python3.5/http/client.py", line 934, in _send_output
    self.send(msg)
  File "/home/jiawenquan/下载/blender-2.79b-linux-glibc219-x86_64/2.79/python/lib/python3.5/http/client.py", line 877, in send
    self.connect()
  File "/home/jiawenquan/下载/blender-2.79b-linux-glibc219-x86_64/2.79/python/lib/python3.5/site-packages/urllib3/connection.py", line 183, in connect
    conn = self._new_conn()
  File "/home/jiawenquan/下载/blender-2.79b-linux-glibc219-x86_64/2.79/python/lib/python3.5/site-packages/urllib3/connection.py", line 169, in _new_conn
    self, "Failed to establish a new connection: %s" % e)
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPConnection object at 0x7fbc138bb128>: Failed to establish a new connection: [Errno 111] Connection refused
Traceback (most recent call last):
  File "/home/jiawenquan/下载/blender-2.79b-linux-glibc219-x86_64/2.79/python/lib/python3.5/site-packages/urllib3/connection.py", line 160, in _new_conn
    (self._dns_host, self.port), self.timeout, **extra_kw)
  File "/home/jiawenquan/下载/blender-2.79b-linux-glibc219-x86_64/2.79/python/lib/python3.5/site-packages/urllib3/util/connection.py", line 80, in create_connection
    raise err
  File "/home/jiawenquan/下载/blender-2.79b-linux-glibc219-x86_64/2.79/python/lib/python3.5/site-packages/urllib3/util/connection.py", line 70, in create_connection
    sock.connect(sa)
ConnectionRefusedError: [Errno 111] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/jiawenquan/下载/blender-2.79b-linux-glibc219-x86_64/2.79/python/lib/python3.5/site-packages/elasticsearch/connection/http_urllib3.py", line 172, in perform_request
    response = self.pool.urlopen(method, url, body, retries=Retry(False), headers=request_headers, **kw)
  File "/home/jiawenquan/下载/blender-2.79b-linux-glibc219-x86_64/2.79/python/lib/python3.5/site-packages/urllib3/connectionpool.py", line 641, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "/home/jiawenquan/下载/blender-2.79b-linux-glibc219-x86_64/2.79/python/lib/python3.5/site-packages/urllib3/util/retry.py", line 344, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "/home/jiawenquan/下载/blender-2.79b-linux-glibc219-x86_64/2.79/python/lib/python3.5/site-packages/urllib3/packages/six.py", line 686, in reraise
    raise value
  File "/home/jiawenquan/下载/blender-2.79b-linux-glibc219-x86_64/2.79/python/lib/python3.5/site-packages/urllib3/connectionpool.py", line 603, in urlopen
    chunked=chunked)
  File "/home/jiawenquan/下载/blender-2.79b-linux-glibc219-x86_64/2.79/python/lib/python3.5/site-packages/urllib3/connectionpool.py", line 355, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "/home/jiawenquan/下载/blender-2.79b-linux-glibc219-x86_64/2.79/python/lib/python3.5/http/client.py", line 1107, in request
    self._send_request(method, url, body, headers)
  File "/home/jiawenquan/下载/blender-2.79b-linux-glibc219-x86_64/2.79/python/lib/python3.5/http/client.py", line 1152, in _send_request
    self.endheaders(body)
  File "/home/jiawenquan/下载/blender-2.79b-linux-glibc219-x86_64/2.79/python/lib/python3.5/http/client.py", line 1103, in endheaders
    self._send_output(message_body)
  File "/home/jiawenquan/下载/blender-2.79b-linux-glibc219-x86_64/2.79/python/lib/python3.5/http/client.py", line 934, in _send_output
    self.send(msg)
  File "/home/jiawenquan/下载/blender-2.79b-linux-glibc219-x86_64/2.79/python/lib/python3.5/http/client.py", line 877, in send
    self.connect()
  File "/home/jiawenquan/下载/blender-2.79b-linux-glibc219-x86_64/2.79/python/lib/python3.5/site-packages/urllib3/connection.py", line 183, in connect
    conn = self._new_conn()
  File "/home/jiawenquan/下载/blender-2.79b-linux-glibc219-x86_64/2.79/python/lib/python3.5/site-packages/urllib3/connection.py", line 169, in _new_conn
    self, "Failed to establish a new connection: %s" % e)
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPConnection object at 0x7fbc138bb128>: Failed to establish a new connection: [Errno 111] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/jiawenquan/PycharmProjects/Match3dTest/test/api_operations_test.py", line 7, in <module>
    api.add('human', stl_file='/home/jiawenquan/下载/humanoid_tri.stl')
  File "/home/jiawenquan/下载/blender-2.79b-linux-glibc219-x86_64/2.79/python/lib/python3.5/site-packages/match3d/api_operations.py", line 83, in add
    _, errs = bulk(self.es, to_insert)
  File "/home/jiawenquan/下载/blender-2.79b-linux-glibc219-x86_64/2.79/python/lib/python3.5/site-packages/elasticsearch/helpers/__init__.py", line 257, in bulk
    for ok, item in streaming_bulk(client, actions, *args, **kwargs):
  File "/home/jiawenquan/下载/blender-2.79b-linux-glibc219-x86_64/2.79/python/lib/python3.5/site-packages/elasticsearch/helpers/__init__.py", line 192, in streaming_bulk
    raise_on_error, *args, **kwargs)
  File "/home/jiawenquan/下载/blender-2.79b-linux-glibc219-x86_64/2.79/python/lib/python3.5/site-packages/elasticsearch/helpers/__init__.py", line 99, in _process_bulk_chunk
    raise e
  File "/home/jiawenquan/下载/blender-2.79b-linux-glibc219-x86_64/2.79/python/lib/python3.5/site-packages/elasticsearch/helpers/__init__.py", line 95, in _process_bulk_chunk
    resp = client.bulk('\n'.join(bulk_actions) + '\n', *args, **kwargs)
  File "/home/jiawenquan/下载/blender-2.79b-linux-glibc219-x86_64/2.79/python/lib/python3.5/site-packages/elasticsearch/client/utils.py", line 76, in _wrapped
    return func(*args, params=params, **kwargs)
  File "/home/jiawenquan/下载/blender-2.79b-linux-glibc219-x86_64/2.79/python/lib/python3.5/site-packages/elasticsearch/client/__init__.py", line 1155, in bulk
    headers={'content-type': 'application/x-ndjson'})
  File "/home/jiawenquan/下载/blender-2.79b-linux-glibc219-x86_64/2.79/python/lib/python3.5/site-packages/elasticsearch/transport.py", line 318, in perform_request
    status, headers_response, data = connection.perform_request(method, url, params, body, headers=headers, ignore=ignore, timeout=timeout)
  File "/home/jiawenquan/下载/blender-2.79b-linux-glibc219-x86_64/2.79/python/lib/python3.5/site-packages/elasticsearch/connection/http_urllib3.py", line 181, in perform_request
    raise ConnectionError('N/A', str(e), e)
elasticsearch.exceptions.ConnectionError: ConnectionError(<urllib3.connection.HTTPConnection object at 0x7fbc138bb128>: Failed to establish a new connection: [Errno 111] Connection refused) caused by: NewConnectionError(<urllib3.connection.HTTPConnection object at 0x7fbc138bb128>: Failed to establish a new connection: [Errno 111] Connection refused)

Process finished with exit code 1

### I tried to change the version of the dependencies, but it didn't work.

**Comment by ayotomiwasalau** [comment]
I have the same error. Help!!!
